[project]
name = "plan10"
version = "0.1.0"
requires-python = "==3.12.*"
dependencies = [
    "torch",          
    "torchaudio",
    "torchvision",
    "torchcodec",
    "torchao",
    "transformers",
    "bitsandbytes", 
    "opencv-python-headless",
    "uniface",
    "omnivoice",
    "librosa",
    "faster-whisper",
    "spacy_download",
    "pip",
    "fastmcp",
    "num2words",
    "diffsynth[all]",
]

[tool.uv]
package = true

[tool.uv.sources]
#diffsynth = { git = "https://github.com/modelscope/DiffSynth-Studio.git", rev = "1e3527b2eb1cefe98c4202f7fc1a1883b45c7b15" }
diffsynth = { git = "https://github.com/modelscope/DiffSynth-Studio.git"}


[tool.setuptools.packages.find]
include = ["plan10*"]

[tool.setuptools.package-data]
plan10 = ["system/*.txt"]

[project.scripts]
config = "plan10.lib.config:main"
image_gen = "plan10.lib.image_gen:main"
anime_gen = "plan10.lib.anime_gen:main"
image_edit = "plan10.lib.image_edit:main"
graphics_gen = "plan10.lib.graphics_gen:main"
camera = "plan10.lib.camera:main"
compositor = "plan10.lib.compositor:main"
decomposer = "plan10.lib.decomposer:main"
dialog = "plan10.lib.dialog:main"
speech_to_video = "plan10.lib.speech_to_video:main"
image_to_video = "plan10.lib.image_to_video:main"
scene_analyzer = "plan10.lib.scene_analyzer:main"
image_analysis = "plan10.lib.image_analysis:main"
captioner = "plan10.lib.captioner:main"
create_registry = "plan10.lib.create_registry:main"
video_creator = "plan10.emergent.video_creator:main"
video_runner = "plan10.emergent.video_runner:main"
video_compositor = "plan10.lib.mmh3:main"
bot = "plan10.bin.bot:main"
bot_cli = "plan10.bin.bot_cli:main"
llm = "plan10.lib.qwen_llm:main"
director = "plan10.lib.director_mmh3:main"

